In [1]:
import pandas as pd
import numpy as np

In [2]:
mem_data = pd.read_csv('mem_data.csv')

In [16]:
mem_data.head()

,MEM_ID,M_STORE_ID,GENDER,BIRTH_DT,BIRTH_SL,ZIP_CD,RGST_DT,VISIT_CNT,SALES_AMT,LAST_VST_DT,USABLE_PNT,USED_PNT,ACC_PNT,USABLE_INIT,SMS
0,7512,305,1,-1,1,0,0,1,69,1097,138,0,114,0,1
1,7511,90,0,2263,0,0,1,1,331,4355,417,0,381,0,1
2,7510,72,1,-1,1,0,1,0,217,5466,235,0,205,0,1
3,7509,90,0,2795,0,0,1,2,440,5989,466,0,427,0,1
5,7508,90,0,380,0,0,1,2,311,3532,332,0,297,0,0